name: "Validate Terraform files"

on:
  push:
    branches:
      - "**"

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        directory: ["./terraform"]
    defaults:
      run:
        working-directory: ${{ matrix.directory }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.3.2

      - name: Run `terraform fmt`
        id: fmt
        run: terraform fmt -diff -check -no-color -recursive

      - name: Run `terraform init`
        id: init
        run: terraform init

      - name: Run `terraform validate`
        id: validate
        run: terraform validate